language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
script:
- npm install
- npm run build
- rimraf build/**/*.map
- npm test
deploy:
- provider: firebase
  token:
    secure: "ToGFSkb4QWGIhXTzgmsbtIXeqrknbWazVN307/Lyo/1biVF+azW1AsA7UniyELb4RMhYrt2RWFAthS+eG7OgYl/ak8ERcuOg3eLSoKWEIJVjA0HSKky+Wssh/ZhCiQBI2QAKizBZLJt2XtuujV72mfbxir4gdj2KlRxd0coKxdeM1LYYjvBPG6KS95f5v+p2K6q6NhCjiO26MSHuuz4gPHG3ebRmQxU2St+NAsiGvrBjMUCLEXRJ7DmhJP3i1tN5OpCQQ02PRydzEL5K5IV4gih99Dq5eDrIOyrbd4Vgy/cUeN2l5WH7BkXWSQYLL8eg3SfRHOJeciqNmYhe0i1LyhbkBPKFxsgWCKnPIh2pwWP6xBjTtYxJnVRzUXJSJPQy6QzWjADTobg5qDF0dznk/SXnqJZAPt/Yw2em8mRkatR03mNqQ5ZngPfSCB4lczWkGusaR6FcOTH58QjNNtlx1dGhTavTDwBqvaL8SYtHrE/gzkmhzF8HdlVH9NczFNWews0mFYJRIjCo9CPLjQ6w3hjwSSFX4ARGd/WmF+a/A+RTwZEujkIBQEVwh0DzrqsqVO2PTeNTbZq9l/Orl6uBY1IPJMTaRtGHUD+GLCUyAQ+qq12wd+/6KmhTeNDYPI/Q/1Ijy3ovanOBss3Aunmir0eYHl0LSpUQAgvygK6b1I4=" 
  project: ffapp-e14be
  skip_cleanup: true
