language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm install
- npm run build
- npm test
deploy:
- provider: heroku
  api_key:
    secure: U78j0RPC6ZdgUahN4hiU8Je5zug3DEEK/iMkbbFahunyTDAqSNilzbnvUAkaw8t2Vs9Z5+ofGVG0aWZbuKeTDJyZZnsdd1F89sdmPNMlzOsnygs+gZylFYRTIjU8uWE1l4tkL70sCKtKZOFwPIXlRQIQVZUQjykmtvmeDM2gPXRDTwg1pTAQFVg8G0E+F0+QniywazGTMKecf3ZOvLdYh44banJ20xMw3BRe0v5yGZzfdOoW4dt3xR8DTCYzQ8/sSclMJFoIYZeH1pEJQQ4GSPqYThfNDFO16jdonZXbDylaC9jkF1aj25kQL4e+2NB9SecPuBNy+ANTKObCWh6mcNP39q8ivtr4g49T8qTmh04UgSKbIGeJudH804v6gOYOPjmKWMG8FRdB81It5/lAh1yw42pTHTYbtg9d1TgA1c2SkoxhmjweM7l87zb/uPEwLWcwHuguWjtiYjTReIAS5xoFdph+mz3kKhm9cyABvhjs94gmfZUVi90Ct9rDWl3zd8hCPa1U0+DgovhL0AGw1VdVmfwOjdMv0YagrTMvsaTh+Y8A1LCfr1eLvICZ4XzhGicTT66gskSnZjwpc4Tu+cA2ftNmf5PacQs+Aly+8Vth1nbC7E89320ZkR4R6NlmwjcLNEBIg6EfEWlrG1h6VVo7bD5Dx5YQm7lsKblogRM=
  app: familyfinance-webapp
  skip_cleanup: true
- provider: firebase
  token:
    secure: "ToGFSkb4QWGIhXTzgmsbtIXeqrknbWazVN307/Lyo/1biVF+azW1AsA7UniyELb4RMhYrt2RWFAthS+eG7OgYl/ak8ERcuOg3eLSoKWEIJVjA0HSKky+Wssh/ZhCiQBI2QAKizBZLJt2XtuujV72mfbxir4gdj2KlRxd0coKxdeM1LYYjvBPG6KS95f5v+p2K6q6NhCjiO26MSHuuz4gPHG3ebRmQxU2St+NAsiGvrBjMUCLEXRJ7DmhJP3i1tN5OpCQQ02PRydzEL5K5IV4gih99Dq5eDrIOyrbd4Vgy/cUeN2l5WH7BkXWSQYLL8eg3SfRHOJeciqNmYhe0i1LyhbkBPKFxsgWCKnPIh2pwWP6xBjTtYxJnVRzUXJSJPQy6QzWjADTobg5qDF0dznk/SXnqJZAPt/Yw2em8mRkatR03mNqQ5ZngPfSCB4lczWkGusaR6FcOTH58QjNNtlx1dGhTavTDwBqvaL8SYtHrE/gzkmhzF8HdlVH9NczFNWews0mFYJRIjCo9CPLjQ6w3hjwSSFX4ARGd/WmF+a/A+RTwZEujkIBQEVwh0DzrqsqVO2PTeNTbZq9l/Orl6uBY1IPJMTaRtGHUD+GLCUyAQ+qq12wd+/6KmhTeNDYPI/Q/1Ijy3ovanOBss3Aunmir0eYHl0LSpUQAgvygK6b1I4=" 
  project: ffapp-e14be
  skip_cleanup: false
